language: java

sudo: false

jdk:
  - openjdk8

before_install:
  - sudo apt-get install nkf && nkf -w ./gradlew > ./gradlew && chmod 755 ./gradlew

script:
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)